CC = gcc
CFLAGS = -g -Wall -Wno-return-type -Wno-implicit-function-declaration -Wno-implicit-int -Wno-incompatible-library-redeclaration -Wno-unused-variable

all: gbn 

gbn:
	$(CC) $(CFLAGS) prog3.c node0.c node1.c node2.c node3.c


clean:
	-rm -f *.o *.out
